### ISSUE TITLE
Wrong regexp when finding instance port

### ISSUE THREAD

**Issue by mauritsvanrees** [4teamwork/ftw.upgrade#163]
In a buildout, I was experimenting with letting Zope listen only on a specific ip address. There are several ways for that. In a `plone.recipe.zope2instance` section I added this:

```
ip-address = 127.0.0.1
```

In development I have set that to `0.0.0.0`. Both settings work as I want.

Problem: `bin/upgrade` no longer works:

```
$ bin/upgrade plone_upgrade --all-sites
Traceback (most recent call last):
  File "bin/upgrade", line 326, in <module>
    sys.exit(ftw.upgrade.command.main())
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/__init__.py", line 197, in main
    UpgradeCommand()()
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/__init__.py", line 154, in __call__
    args.func(args)
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 123, in func_wrapper
    site = get_plone_site_by_args(args, APIRequestor(auth))
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 257, in get_plone_site_by_args
    sites = get_sites(requestor)
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 274, in get_sites
    response = requestor.GET('list_plone_sites')
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 33, in GET
    return self._make_request('GET', action, site=site, **kwargs)
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 39, in _make_request
    url = get_api_url(action, site=site or self.site)
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 161, in get_api_url
    url = get_zope_url()
  File "/Users/maurits/shared-eggs/cp27m/ftw.upgrade-2.10.0-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 199, in get_zope_url
    raise NoRunningInstanceFound()
ftw.upgrade.command.jsonapi.NoRunningInstanceFound
```

I initially thought that maybe ftw.upgrade tries to connect in a way that is refused in my new config. So I commented out the ip-address line and tried again, with the same error.

The problem is in the regular expression in [`get_instance_port`](https://github.com/4teamwork/ftw.upgrade/blob/2.10.0/ftw/upgrade/command/jsonapi.py#L218-L222): `address ([\d.]*:)?(\d+)`. This finds my `ip-address = 127.0.0.1` line and trips up.

So the regexp should be fixed to not find this one.
And it should not find comments: I commented out the ip-address line with a hash, but the regexp found it anyway.

I tried a bit, but it is tricky. Perhaps best would be to try it line by line, something like this:

```
pattern = re.compile(r'^address ([\d.]*:)?(\d+)')
for line in zconf.text():
    line = line.strip()
    if not line or line.startswith('#') or 'address' not in line:
        continue
    match = re.search(pattern, line)
    ...
```

**Comment by jone** [comment]
The `ip-address` option is not respected indeed.
I found the simple solution to just expect a whitespace before the `address` string. The whitespace can either be a newline or an indentation, but it will not match for `ip-address`.

@mauritsvanrees the pull request #164 fixes this issue 😉

**Comment by mauritsvanrees** [comment]
Your PR works. Thanks!
